# Import Library

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Data Understanding

## Import Dataset dan Sumber, Nama, Format, serta Tujuan Dataset

In [2]:
data = pd.read_csv("Sample - Superstore.csv", encoding="cp1252")
df = pd.DataFrame(data)
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

Sumber = kaggle (https://www.kaggle.com/datasets/vivek468/superstore-dataset-final/data)
Nama = Sample - Superstore.csv
Format = CSV
Tujuan = Analisis Performa Pelanggan dan Produk

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

Jumlah Baris = 9994
Jumlah Kolom = 21

Deskripsi Kolom =
Row ID        = ID unik setiap baris
Order ID      = ID pesanan unik
Order Date    = Tanggal pemesanan produk
Ship Date     = Tanggal pengiriman produk
Ship Mode     = Metode pengiriman produk
Customer ID   = ID unik setiap pelanggan
Customer Name = Nama pelanggan
Segment       = Segmen tempat tinggal pelanggan
Country       = Negara tempat tinggal pelanggan
City          = Kota tempat tinggal pelanggan
State         = Provinsi tempat tinggal pelanggan
Postal Code   = Kode pos pelanggan
Region        = Wilayah tempat pelanggan
Product ID    = ID unik produk
Category      = Kategori produk yang dipesan
Sub-Category  = Subkategori produk yang dipesan
Product Name  = Nama produk
Sales         = Nilai penjualan produk
Quantity      = Jumlah/kuantitas produk
Discount      = Diskon yang diberikan
Profit        = Keuntungan/kerugian yang diperoleh

Tipe Data
Tipe data integer terdapat 3 kolom = Row ID, Postal Code dan Quantity
Tipe data float terdapat 3 kolom   = Sales, Discount, Profit
Tipe data string terdapat 15 kolom = Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Region, 
                                     Product ID, Category, Sub-Category, dan Product Name

## Data Exploration

### Membuat Copy Dataset

In [4]:
df_copy = df.copy()

### Tipe Data

Tipe data kolom Order Date dan Ship Date kurang tepat dikarenakan tanggal masih bertipe data string

### Inkonsistensi Data

In [5]:
df_copy["Order ID"].unique()

<ArrowStringArray>
['CA-2016-152156', 'CA-2016-138688', 'US-2015-108966', 'CA-2014-115812',
 'CA-2017-114412', 'CA-2016-161389', 'US-2015-118983', 'CA-2014-105893',
 'CA-2014-167164', 'CA-2014-143336',
 ...
 'US-2016-103674', 'US-2015-151435', 'CA-2017-163566', 'US-2016-157728',
 'CA-2015-100251', 'CA-2016-125794', 'CA-2017-163629', 'CA-2014-110422',
 'CA-2017-121258', 'CA-2017-119914']
Length: 5009, dtype: str

In [6]:
df_copy["Order Date"].unique()

<ArrowStringArray>
[ '11/8/2016',  '6/12/2016', '10/11/2015',   '6/9/2014',  '4/15/2017',
  '12/5/2016', '11/22/2015', '11/11/2014',  '5/13/2014',  '8/27/2014',
 ...
 '10/11/2016',  '6/18/2014',  '2/28/2017',   '5/9/2015',  '11/6/2014',
 '12/29/2015',   '4/3/2014',   '6/3/2016',  '4/12/2015',  '1/21/2014']
Length: 1237, dtype: str

In [7]:
df_copy["Ship Date"].unique()

<ArrowStringArray>
['11/11/2016',  '6/16/2016', '10/18/2015',  '6/14/2014',  '4/20/2017',
 '12/10/2016', '11/26/2015', '11/18/2014',  '5/15/2014',   '9/1/2014',
 ...
   '4/6/2017',  '5/13/2015',  '8/19/2014',  '1/20/2017',  '3/28/2015',
  '8/25/2016',  '1/27/2014',  '5/23/2015',  '1/23/2014',   '3/3/2017']
Length: 1334, dtype: str

In [8]:
df_copy["Ship Mode"].unique()

<ArrowStringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [9]:
df_copy["Customer ID"].unique()

<ArrowStringArray>
['CG-12520', 'DV-13045', 'SO-20335', 'BH-11710', 'AA-10480', 'IM-15070',
 'HP-14815', 'PK-19075', 'AG-10270', 'ZD-21925',
 ...
 'FW-14395', 'LC-16960', 'HE-14800', 'BD-11560', 'HD-14785', 'CJ-11875',
 'RS-19870', 'SC-20845', 'RE-19405', 'SM-20905']
Length: 793, dtype: str

In [10]:
df_copy["Customer Name"].unique()

<ArrowStringArray>
[       'Claire Gute',    'Darrin Van Huff',     'Sean O'Donnell',
    'Brosina Hoffman',       'Andrew Allen',       'Irene Maddox',
      'Harold Pawlan',          'Pete Kriz',    'Alejandro Grove',
 'Zuschuss Donatelli',
 ...
     'Fred Wasserman',    'Lindsay Castell',       'Harold Engle',
     'Brendan Dodson',      'Harold Dahlen',       'Carl Jackson',
         'Roy Skaria',         'Sung Chung',    'Ricardo Emerson',
  'Susan MacKendrick']
Length: 793, dtype: str

In [11]:
df_copy["Segment"].unique()

<ArrowStringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

In [12]:
df_copy["Country"].unique()

<ArrowStringArray>
['United States']
Length: 1, dtype: str

In [13]:
df_copy["City"].unique()

<ArrowStringArray>
[        'Henderson',       'Los Angeles',   'Fort Lauderdale',
           'Concord',           'Seattle',        'Fort Worth',
           'Madison',       'West Jordan',     'San Francisco',
           'Fremont',
 ...
        'Hagerstown',       'East Orange', 'Arlington Heights',
            'Oswego',       'Coon Rapids',      'San Clemente',
   'San Luis Obispo',        'Springdale',              'Lodi',
             'Mason']
Length: 531, dtype: str

In [14]:
df_copy["State"].unique()

<ArrowStringArray>
[            'Kentucky',           'California',              'Florida',
       'North Carolina',           'Washington',                'Texas',
            'Wisconsin',                 'Utah',             'Nebraska',
         'Pennsylvania',             'Illinois',            'Minnesota',
             'Michigan',             'Delaware',              'Indiana',
             'New York',              'Arizona',             'Virginia',
            'Tennessee',              'Alabama',       'South Carolina',
               'Oregon',             'Colorado',                 'Iowa',
                 'Ohio',             'Missouri',             'Oklahoma',
           'New Mexico',            'Louisiana',          'Connecticut',
           'New Jersey',        'Massachusetts',              'Georgia',
               'Nevada',         'Rhode Island',          'Mississippi',
             'Arkansas',              'Montana',        'New Hampshire',
             'Maryland', 'District of Columbia',               'Kansas',
              'Vermont',                'Maine',         'South Dakota',
                'Idaho',         'North Dakota',              'Wyoming',
        'West Virginia']
Length: 49, dtype: str

In [15]:
df_copy["Region"].unique()

<ArrowStringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [16]:
df_copy["Product ID"].unique()

<ArrowStringArray>
['FUR-BO-10001798', 'FUR-CH-10000454', 'OFF-LA-10000240', 'FUR-TA-10000577',
 'OFF-ST-10000760', 'FUR-FU-10001487', 'OFF-AR-10002833', 'TEC-PH-10002275',
 'OFF-BI-10003910', 'OFF-AP-10002892',
 ...
 'OFF-LA-10004677', 'FUR-CH-10002780', 'OFF-EN-10001535', 'TEC-MA-10003493',
 'TEC-AC-10002380', 'TEC-PH-10002817', 'TEC-MA-10003589', 'OFF-AP-10003099',
 'TEC-PH-10002645', 'OFF-ST-10001627']
Length: 1862, dtype: str

In [17]:
df_copy["Category"].unique()

<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [18]:
df_copy["Sub-Category"].unique()

<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [19]:
df_copy["Product Name"].unique()

<ArrowStringArray>
[                               'Bush Somerset Collection Bookcase',
      'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
        'Self-Adhesive Address Labels for Typewriters by Universal',
                    'Bretford CR4500 Series Slim Rectangular Table',
                                   'Eldon Fold 'N Roll Cart System',
 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood',
                                                       'Newell 322',
                                   'Mitel 5320 IP Phone VoIP phone',
             'DXL Angle-View Binders with Locking Rings by Samsill',
                                 'Belkin F5C206VTEL 6 Outlet Surge',
 ...
  'Self-Adhesive Address Labels for Typewriters with Dispenser Box',
             'Office Star - Task Chair with Contemporary Loop Arms',
                                              'Grip Seal Envelopes',
                              'Penpower WorldCard Pro Card Scanner',
                     'Sony 8GB Class 10 Micro SDHC R40 Memory Card',
                                  'RCA ViSYS 25425RE1 Corded phone',
                                     'Cisco 8961 IP Phone Charcoal',
                                      'Eureka Hand Vacuum, Bagless',
                                                            'LG G2',
           'Eldon Jumbo ProFile Portable File Boxes Graphite/Black']
Length: 1850, dtype: str

Tidak terdapat Inkonsistensi Data

### Missing Value

In [20]:
jumlah_missing = df_copy.isnull().sum() # Jumlah missing value
persentase_missing = jumlah_missing/len(df_copy)*100 # Persentase missing value

In [21]:
print(f"Jumlah Missing Value = \n{jumlah_missing}")
print(f"Persentase Missing Value = \n{persentase_missing}")

Jumlah Missing Value =
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
Persentase Missing Value =
Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

Tidak Terdapat Missing Value

### Duplicate Value

In [22]:
jumlah_duplicate = df_copy.duplicated().sum()
persentase_duplicate = jumlah_duplicate/len(df_copy)*100

In [23]:
print(f"Jumlah Duplicate Value = \n{jumlah_duplicate}")
print(f"Persentase Duplicate Value = \n{persentase_duplicate}")

Jumlah Duplicate Value =
0
Persentase Duplicate Value =
0.0

Tidak Terdapat Duplicate Value

### Outlier

#### Label Encoder

In [24]:
le = LabelEncoder()

In [25]:
df_copy_2 = df_copy.copy()

In [26]:
'''Membuat Label Encoder Pada Kolom Dengan Tipe Data String'''
df_copy_2["Order ID Code"] = le.fit_transform(df_copy_2["Order ID"])
df_copy_2["Order Date Code"] = le.fit_transform(df_copy_2["Order Date"])
df_copy_2["Ship Date Code"] = le.fit_transform(df_copy_2["Ship Date"])
df_copy_2["Ship Mode Code"] = le.fit_transform(df_copy_2["Ship Mode"])
df_copy_2["Customer ID Code"] = le.fit_transform(df_copy_2["Customer ID"])
df_copy_2["Customer Name Code"] = le.fit_transform(df_copy_2["Customer Name"])
df_copy_2["Segment Code"] = le.fit_transform(df_copy_2["Segment"])
df_copy_2["Country Code"] = le.fit_transform(df_copy_2["Country"])
df_copy_2["City Code"] = le.fit_transform(df_copy_2["City"])
df_copy_2["State Code"] = le.fit_transform(df_copy_2["State"])
df_copy_2["Region Code"] = le.fit_transform(df_copy_2["Region"])
df_copy_2["Product ID Code"] = le.fit_transform(df_copy_2["Product ID"])
df_copy_2["Category Code"] = le.fit_transform(df_copy_2["Category"])
df_copy_2["Sub-Category Code"] = le.fit_transform(df_copy_2["Sub-Category"])
df_copy_2["Product Name Code"] = le.fit_transform(df_copy_2["Product Name"])

#### Cek Outlier Dengan IQR

In [27]:
df_copy_outlier = df_copy_2[[
    "Order ID Code",
    "Order Date Code",
    "Ship Date Code",
    "Ship Mode Code",
    "Customer ID Code",
    "Customer Name Code",
    "Segment Code",
    "Country Code",
    "City Code",
    "State Code",
    "Region Code",
    "Product ID Code",
    "Category Code",
    "Sub-Category Code",
    "Product Name Code",
    "Row ID",
    "Postal Code",
    "Quantity",
    "Sales",
    "Discount",
    "Profit"
]]

In [28]:
kolom_outlier = df_copy_outlier.columns

In [29]:
for i in kolom_outlier :
    q1 = df_copy_outlier[i].quantile(0.25)
    q3 = df_copy_outlier[i].quantile(0.75)
    iqr = (q3 - q1)
    upper = q3 + (iqr*1.5)
    lower = q1 - (iqr*1.5)
    outlier = (df_copy_outlier[i] < lower) | (df_copy_outlier[i] > upper)
    jumlah_outlier = outlier.sum()
    persentase_outlier = jumlah_outlier/len(df_copy_outlier)*100
    print(f"Jumlah Outlier Kolom {i} = {jumlah_outlier}")
    print(f"Persentase Outlier Kolom {i} = {persentase_outlier:.2f}%\n")

Jumlah Outlier Kolom Order ID Code = 0
Persentase Outlier Kolom Order ID Code = 0.00%

Jumlah Outlier Kolom Order Date Code = 0
Persentase Outlier Kolom Order Date Code = 0.00%

Jumlah Outlier Kolom Ship Date Code = 0
Persentase Outlier Kolom Ship Date Code = 0.00%

Jumlah Outlier Kolom Ship Mode Code = 1538
Persentase Outlier Kolom Ship Mode Code = 15.39%

Jumlah Outlier Kolom Customer ID Code = 0
Persentase Outlier Kolom Customer ID Code = 0.00%

Jumlah Outlier Kolom Customer Name Code = 0
Persentase Outlier Kolom Customer Name Code = 0.00%

Jumlah Outlier Kolom Segment Code = 0
Persentase Outlier Kolom Segment Code = 0.00%

Jumlah Outlier Kolom Country Code = 0
Persentase Outlier Kolom Country Code = 0.00%

Jumlah Outlier Kolom City Code = 0
Persentase Outlier Kolom City Code = 0.00%

Jumlah Outlier Kolom State Code = 0
Persentase Outlier Kolom State Code = 0.00%

Jumlah Outlier Kolom Region Code = 0
Persentase Outlier Kolom Region Code = 0.00%

Jumlah Outlier Kolom Product ID Code = 0
Persentase Outlier Kolom Product ID Code = 0.00%

Jumlah Outlier Kolom Category Code = 3968
Persentase Outlier Kolom Category Code = 39.70%

Jumlah Outlier Kolom Sub-Category Code = 0
Persentase Outlier Kolom Sub-Category Code = 0.00%

Jumlah Outlier Kolom Product Name Code = 0
Persentase Outlier Kolom Product Name Code = 0.00%

Jumlah Outlier Kolom Row ID = 0
Persentase Outlier Kolom Row ID = 0.00%

Jumlah Outlier Kolom Postal Code = 0
Persentase Outlier Kolom Postal Code = 0.00%

Jumlah Outlier Kolom Quantity = 170
Persentase Outlier Kolom Quantity = 1.70%

Jumlah Outlier Kolom Sales = 1167
Persentase Outlier Kolom Sales = 11.68%

Jumlah Outlier Kolom Discount = 856
Persentase Outlier Kolom Discount = 8.57%

Jumlah Outlier Kolom Profit = 1881
Persentase Outlier Kolom Profit = 18.82%

Terdapat Outlier Kolom Ship Mode Code Sebesar 15.39%
Terdapat Outlier Kolom Category Code Sebesar 39.70%
Terdapat Outlier Kolom Quantity Sebesar 1.70%
Terdapat Outlier Kolom Sales Sebesar 11.68%
Terdapat Outlier Kolom Discount Sebesar 8.57%
Terdapat Outlier Kolom Profit Sebesar 18.82%

## Insight Data Exploration

- Tidak terdapat inkonsistensi, missing value, dan duplicate value sehingga tidak ada penanganan
- Tipe data kolom Order Date dan Ship Date kurang tepat dikarenakan tanggal masih bertipe data string. Disarankan tipe diubah menjadi datetime
- Terdapat outlier pada kolom :
    Ship Mode Code Sebesar 15.39%
    Category Code Sebesar 39.70%
    Quantity Sebesar 1.70%
    Sales Sebesar 11.68%
    Discount Sebesar 8.57%
    Profit Sebesar 18.82%

# Data Preparation

## Data Cleaning

### Inkonsistensi, Missing Value, dan Duplicate Value

Tidak terdapat inkonsistensi, missing value, dan duplicate value sehingga tidak ada penanganan

### Tipe Data

In [30]:
df_copy["Order Date"] = pd.to_datetime(df_copy["Order Date"], format = "%m/%d/%Y")
df_copy["Ship Date"] = pd.to_datetime(df_copy["Ship Date"], format = "%m/%d/%Y")

In [31]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB

Tipe data kolom Order Date dan Ship Date berhasil diubah menjadi tipe datetime

### Outlier

Penanganan outlier berupa mengkonfirmasi kembali datanya kepada pemberi data. Apakah datanya valid atau tidak
Apabila pemberi data menyatakan bahwa data yang berupa outlier adalah valid, maka tidak ada penanganan outlier

# Export Data Bersih

In [32]:
df_copy.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

df_copy sudah bersih dan akan diexport

In [33]:
'''Export df_copy menjadi excel'''
df_copy.to_excel("Sample - Superstore Clean Dataset.xlsx")